In [2]:
import cv2
import numpy as np 
import random
import cv2
import os
from scipy.ndimage import convolve
import imutils
from skimage.filters import threshold_adaptive


In [6]:
image = cv2.imread('test_card.jpg')
# print(image.shape)
image = cv2.resize(image,(659,890),interpolation = cv2.INTER_AREA)
print(image.shape)
orig_height, orig_width = image.shape[:2]
ratio = image.shape[0] / 500.0

orig = image.copy()
image = imutils.resize(image, height = 500)
print(image.shape)
Original_Area = orig_height * orig_width

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print("gray image shape :: "+ str(gray.shape))
gray = cv2.GaussianBlur(gray, (5, 5), 0)
print(" GaussianBlur shape :: "+ str(gray.shape))
edged = cv2.Canny(gray, 75, 200)
print("edged image shape :: "+ str(edged.shape))

cv2.imshow("Image", image)
cv2.imshow("Edged", edged)
cv2.waitKey(0)

_, contours, hierarchy  = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
contours = sorted(contours, key = cv2.contourArea, reverse = True)[:5]
print("one contours shape and len ::"+str(contours[0].shape) + str(len(contours)))
i = 0
for c in contours:

    area = cv2.contourArea(c)
    i+=1
#     if area < (Original_Area/3):
#         print("Image Invalid  -> "+str(i)+str(c.shape))
#         continue
    
    peri = cv2.arcLength(c, True)  #perimater of contours
    print("perimeter of one contour"+str(peri))
    epsilon = 0.001*peri
    #approx return the just one numpy array
    approx = cv2.approxPolyDP(c, epsilon, True) #use to approximate shape if squrare doesn't detect
    print("approx::"+str(approx))
    
    if len(approx) == 4:
        screenCnt = approx
        break

#to draw all aproximation function aspect array of contours not just on numpy array
cv2.drawContours(image, [screenCnt], -1, (0, 255, 0), 2) # -1 draw all contours or 3 draw 3rd contour or 4th is thickness
cv2.imshow("Outline", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(890, 659, 3)
(500, 370, 3)
gray image shape :: (500, 370)
 GaussianBlur shape :: (500, 370)
edged image shape :: (500, 370)
one contours shape and len ::(77, 1, 2)5
perimeter of one contour1245.0538227558136
approx::[[[315  65]]

 [[ 43  68]]

 [[ 39  70]]

 [[ 34  82]]

 [[ 33 393]]

 [[ 39 405]]

 [[ 96 406]]

 [[317 400]]

 [[323 396]]

 [[327 384]]

 [[323  80]]

 [[320  70]]]
perimeter of one contour1242.7106765508652
approx::[[[314  65]]

 [[320  71]]

 [[323  80]]

 [[327 384]]

 [[323 395]]

 [[317 400]]

 [[ 96 406]]

 [[ 40 405]]

 [[ 33 393]]

 [[ 34  82]]

 [[ 39  71]]

 [[ 43  68]]]
perimeter of one contour296.2426406145096
approx::[[[ 51 363]]

 [[ 51 390]]

 [[ 52 391]]

 [[ 52 392]]

 [[170 392]]

 [[170 363]]

 [[169 363]]

 [[168 362]]

 [[ 52 362]]]
perimeter of one contour293.899494767189
approx::[[[ 51 364]]

 [[ 53 362]]

 [[168 362]]

 [[170 364]]

 [[170 391]]

 [[169 392]]

 [[ 53 392]]

 [[ 51 390]]]
perimeter of one contour226.911687374115
approx::[[[ 69 172

NameError: name 'screenCnt' is not defined

In [ ]:
cv2.drawContours?