In [1]:
# Imports
# Please refer to requirements.txt for a full list of all libraries and their versions used in this project.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import cv2
import os
from zipfile import ZipFile
import time
from datetime import datetime
import itertools

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D, AveragePooling2D, GlobalAveragePooling2D
from tensorflow.keras import utils
from tensorflow.keras.callbacks import TensorBoard, ModelCheckpoint

# Setting random seeds to reduce the amount of randomness in the neural net weights and results.
# The results may still not be exactly reproducible.
np.random.seed(42)
tf.random.set_seed(42)

In [116]:
dataset = pd.read_csv('dataset.csv')

/home/falcon-puneet/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [117]:
s = str(dataset['image'].values[0])

In [118]:
gray = cv2.cvtColor(cv2.imread(s), cv2.COLOR_BGR2GRAY).
gray

(200, 200)

In [119]:
X = dataset.drop(columns=['target_age','target_gender','target_race','age'])
y = dataset.drop(columns=['image','target_gender','target_race','age'])

In [120]:
print(X.shape,y.shape)

(237080, 1) (237080, 1)


In [121]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=42)

In [122]:
num_classes = 7

def _parse_label(label):
    label = tf.one_hot(label, num_classes)
    return label

def _parse_filename(name):
    return cv2.cvtColor(cv2.imread(s), cv2.COLOR_BGR2GRAY)

In [ ]:
y_train = y_train['target_age'].map(_parse_label) 
X_train = X_train['image'].map(_parse_filename)

In [102]:
X

<tf.Tensor: shape=(7,), dtype=float32, numpy=array([0., 0., 0., 0., 1., 0., 0.], dtype=float32)>

In [93]:
# Getting the dataset ready for the neural network.
# Using the tensor vectors defined above, accessing the images in the dataset and passing them through the function defined above.

train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train_tensor))
train_dataset = train_dataset.map(_parse_function)
# train_dataset = train_dataset.batch(512)    # Same as batch_size hyperparameter in model.fit() below.
# train_aug_dataset = train_aug_dataset.repeat(3)

# test_dataset = tf.data.Dataset.from_tensor_slices((X_test_tensor,y_test_tensor))
# test_dataset = test_dataset.map(_parse_function)
# # test_dataset = test_dataset.repeat(3)
# test_dataset = test_dataset.batch(512)    # Same as batch_size hyperparameter in model.fit() below.

Tensor("args_0:0", shape=(1,), dtype=string)


In [91]:
for x in train_dataset:
    print(x)
    break

(<tf.Tensor: shape=(1,), dtype=string, numpy=
array([b'../../age_detection/new_face_dataset/75_1_0_20170110181743217_fliplr_rot_neg20.jpg'],
      dtype=object)>, <tf.Tensor: shape=(1, 7), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>)
